services:
#----------------------- Kafka--------------------
  kafka:
    image: confluentinc/confluent-local:latest
    container_name: kafka
    ports:
      # Using 9092 for local dev
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: "1"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"

      # Listeners - host apps use localhost:9092 and containers use kafka:29092
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"

      CLUSTER_ID: "mkV5YH2fT2C2r1K0N0a0Qw"

      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
    volumes:
      - kafka-data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD", "bash", "-lc", "kafka-broker-api-versions --bootstrap-server localhost:9092 >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 12
#----------------------- Kafka Ui ----------------
  kafbat-ui:
    container_name: kafbat-ui
    image: ghcr.io/kafbat/kafka-ui:latest
    ports:
      - "8000:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
#----------------------- postgres ----------------
  database:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/18/docker
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h 127.0.0.1" ]
      interval: 5s
      timeout: 5s
      retries: 20
#--------------------- Services ------------------
  feedback-api:
    build:
      context: ./tsg-9.27-devinjosh-feedback-api
      dockerfile: Dockerfile
    container_name: feedback-api
    profiles: ["app"]   # <- only starts when you enable the "app" profile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    depends_on:
      database:
        condition: service_healthy
      kafka:
        condition: service_healthy
    ports:
      - "8082:8082"
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://localhost:8082/api/v1/health" ]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 20s
    restart: on-failure

  analytics-consumer:
    build:
      context: ./tsg-9.27-devinjosh-feedback-analytics-consumer
      dockerfile: Dockerfile
    container_name: feedback-analytics-consumer
    profiles: ["app"]
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_KAFKA_CONSUMER_GROUP: feedback-analytics-consumer
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "8081:8081"
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://localhost:8081/health" ]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 20s
    restart: on-failure

  frontend-ui:
    build:
      context: ./tsg-9.27-devinjosh-frontend-feedback-ui
      dockerfile: Dockerfile
    container_name: frontend-ui
    ports:
      - "5173:80"
    profiles: ["app"]
# docker compose up -d : will run just kafka and postgres - use this for local dev
# docker compose --profile app up -d : will spin up everything

volumes:
  kafka-data:
  postgres_data:
